-- Missing Lead Way Petrol Station entries from FUEL CONSUMPTION AND PAYMENT RECONCILIATION SHEET UPDATED (1).xlsx.
-- Generated by comparing workbook entries against supabase/seeds/lead_way_fuel.sql.
-- Workbook rows: 113. Existing seed matches: 97. Missing rows: 16.
begin;

insert into public.members (id, name, phone, joined_at, status, member_category, member_tags, business_name, vehicle_plate, fee_membership, fee_card, fee_sticker)
values
  ('SBC0413K', 'LINDA WANJIRU', '0700000413', '2025-11-15'::date, 'active', 'locomotive', array['member','locomotive']::text[], 'Fuel customer', null, true, true, true),
  ('SBC0458K', 'KEVIN MANYEKI', '0700000458', '2025-11-15'::date, 'active', 'locomotive', array['member','locomotive']::text[], 'Fuel customer', 'KDW 221X', true, true, true)
on conflict (id) do update set
  member_category = excluded.member_category,
  member_tags = array(select distinct unnest(coalesce(public.members.member_tags, '{}'::text[]) || excluded.member_tags)),
  vehicle_plate = coalesce(nullif(public.members.vehicle_plate, ''), excluded.vehicle_plate),
  updated_at = now();

insert into public.suppliers (id, name, kind, phone, contact_person, location, notes, status, member_id, supplier_type, registration_category, business_registration_number, physical_location, mpesa_paybill_till, supplier_class)
values ('SUP-LEAD-WAY-PETROL', 'LEAD WAY PETROL STATION', 'fuel', '0700000000', 'Accounts', 'Kiambu', 'Seeded from fuel consumption and payment reconciliation workbook.', 'active', 'SUP0001K', 'company', 'goods', 'LEAD-WAY-PETROL', 'Kiambu', 'LEADWAY', 'normal')
on conflict (id) do update set name = excluded.name, kind = excluded.kind, notes = excluded.notes, updated_at = now();

create temp table leadway2_fuel_seed (
  member_id text not null,
  member_name text not null,
  plate text not null,
  fuel_amount numeric(14,2) not null,
  entry_date date not null
) on commit drop;

insert into leadway2_fuel_seed (member_id, member_name, plate, fuel_amount, entry_date)
values
  ('SBC0413K', 'LINDA WANJIRU', '', 3200.00, '2026-01-19'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 2350.00, '2026-01-26'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 3300.00, '2026-02-01'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 3300.00, '2026-02-12'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 3300.00, '2026-02-16'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 1050.00, '2026-02-19'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 3300.00, '2026-02-27'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 3300.00, '2026-03-04'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 3560.00, '2026-03-09'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 2200.00, '2026-03-12'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 5000.00, '2026-03-18'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 3300.00, '2026-03-23'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 3300.00, '2026-03-24'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 2250.00, '2026-03-24'::date),
  ('SBC0413K', 'LINDA WANJIRU', '', 3300.00, '2026-03-29'::date),
  ('SBC0458K', 'KEVIN MANYEKI', 'KDW 221X', 3000.00, '2026-05-06'::date);

insert into public.supplier_fulfillment_requests (id, supplier_id, member_id, kind, amount, detail, status, fulfilled_at, commodity_name, vehicle_plate, fuel_type, driver_member_id)
select
  'SFR-LW-MISSING-' || member_id || '-' || to_char(entry_date, 'YYYYMMDD') || '-' || row_number() over (partition by member_id, entry_date order by fuel_amount, plate),
  'SUP-LEAD-WAY-PETROL', member_id, 'fuel', fuel_amount,
  jsonb_build_object('source','leadway2.sql','memberName',member_name,'plate',plate,'entryDate',entry_date),
  'fulfilled', entry_date::timestamptz, 'Fuel', plate, 'Fuel', member_id
from leadway2_fuel_seed
on conflict (id) do update set amount = excluded.amount, detail = excluded.detail, updated_at = now();

insert into public.system_outflows (id, kind, amount, receiver_name, method, member_id, supplier_id, note, created_at)
select
  'OUT-LW-MISSING-' || member_id || '-' || to_char(entry_date, 'YYYYMMDD') || '-' || row_number() over (partition by member_id, entry_date order by fuel_amount, plate),
  'supplier_payment', fuel_amount, 'LEAD WAY PETROL STATION', 'supplier_credit', member_id, 'SUP-LEAD-WAY-PETROL',
  'Sauti payment to Lead Way for missing workbook fuel consumption entry.', entry_date::timestamptz
from leadway2_fuel_seed
on conflict (id) do nothing;

commit;
