/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SupportInboxRouteImport } from './routes/support-inbox'
import { Route as StaffMgmtRouteImport } from './routes/staff-mgmt'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SharesRouteImport } from './routes/shares'
import { Route as SecretKeysRouteImport } from './routes/secret-keys'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PettycashRouteImport } from './routes/pettycash'
import { Route as MemosRouteImport } from './routes/memos'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as FeesPolicyRouteImport } from './routes/fees-policy'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMpesaQueueRouteImport } from './routes/api/mpesa.queue'
import { Route as ApiAiScanMpesaRouteImport } from './routes/api/ai.scan-mpesa'
import { Route as ApiAiChatRouteImport } from './routes/api/ai.chat'
import { Route as ApiPublicMpesaValidationRouteImport } from './routes/api/public/mpesa.validation'
import { Route as ApiPublicMpesaStkpushRouteImport } from './routes/api/public/mpesa.stkpush'
import { Route as ApiPublicMpesaDiagnoseRouteImport } from './routes/api/public/mpesa.diagnose'
import { Route as ApiPublicMpesaConfirmationRouteImport } from './routes/api/public/mpesa.confirmation'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportInboxRoute = SupportInboxRouteImport.update({
  id: '/support-inbox',
  path: '/support-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffMgmtRoute = StaffMgmtRouteImport.update({
  id: '/staff-mgmt',
  path: '/staff-mgmt',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SharesRoute = SharesRouteImport.update({
  id: '/shares',
  path: '/shares',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretKeysRoute = SecretKeysRouteImport.update({
  id: '/secret-keys',
  path: '/secret-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PettycashRoute = PettycashRouteImport.update({
  id: '/pettycash',
  path: '/pettycash',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosRoute = MemosRouteImport.update({
  id: '/memos',
  path: '/memos',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesPolicyRoute = FeesPolicyRouteImport.update({
  id: '/fees-policy',
  path: '/fees-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaQueueRoute = ApiMpesaQueueRouteImport.update({
  id: '/api/mpesa/queue',
  path: '/api/mpesa/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiScanMpesaRoute = ApiAiScanMpesaRouteImport.update({
  id: '/api/ai/scan-mpesa',
  path: '/api/ai/scan-mpesa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaValidationRoute =
  ApiPublicMpesaValidationRouteImport.update({
    id: '/api/public/mpesa/validation',
    path: '/api/public/mpesa/validation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpesaStkpushRoute = ApiPublicMpesaStkpushRouteImport.update({
  id: '/api/public/mpesa/stkpush',
  path: '/api/public/mpesa/stkpush',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaDiagnoseRoute = ApiPublicMpesaDiagnoseRouteImport.update({
  id: '/api/public/mpesa/diagnose',
  path: '/api/public/mpesa/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaConfirmationRoute =
  ApiPublicMpesaConfirmationRouteImport.update({
    id: '/api/public/mpesa/confirmation',
    path: '/api/public/mpesa/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/approvals': typeof ApprovalsRoute
  '/attendance': typeof AttendanceRoute
  '/fees-policy': typeof FeesPolicyRoute
  '/investors': typeof InvestorsRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/memos': typeof MemosRoute
  '/pettycash': typeof PettycashRoute
  '/policies': typeof PoliciesRoute
  '/portal': typeof PortalRoute
  '/reports': typeof ReportsRoute
  '/savings': typeof SavingsRoute
  '/secret-keys': typeof SecretKeysRoute
  '/shares': typeof SharesRoute
  '/staff': typeof StaffRoute
  '/staff-mgmt': typeof StaffMgmtRoute
  '/support-inbox': typeof SupportInboxRoute
  '/transactions': typeof TransactionsRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/scan-mpesa': typeof ApiAiScanMpesaRoute
  '/api/mpesa/queue': typeof ApiMpesaQueueRoute
  '/api/public/mpesa/confirmation': typeof ApiPublicMpesaConfirmationRoute
  '/api/public/mpesa/diagnose': typeof ApiPublicMpesaDiagnoseRoute
  '/api/public/mpesa/stkpush': typeof ApiPublicMpesaStkpushRoute
  '/api/public/mpesa/validation': typeof ApiPublicMpesaValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/approvals': typeof ApprovalsRoute
  '/attendance': typeof AttendanceRoute
  '/fees-policy': typeof FeesPolicyRoute
  '/investors': typeof InvestorsRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/memos': typeof MemosRoute
  '/pettycash': typeof PettycashRoute
  '/policies': typeof PoliciesRoute
  '/portal': typeof PortalRoute
  '/reports': typeof ReportsRoute
  '/savings': typeof SavingsRoute
  '/secret-keys': typeof SecretKeysRoute
  '/shares': typeof SharesRoute
  '/staff': typeof StaffRoute
  '/staff-mgmt': typeof StaffMgmtRoute
  '/support-inbox': typeof SupportInboxRoute
  '/transactions': typeof TransactionsRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/scan-mpesa': typeof ApiAiScanMpesaRoute
  '/api/mpesa/queue': typeof ApiMpesaQueueRoute
  '/api/public/mpesa/confirmation': typeof ApiPublicMpesaConfirmationRoute
  '/api/public/mpesa/diagnose': typeof ApiPublicMpesaDiagnoseRoute
  '/api/public/mpesa/stkpush': typeof ApiPublicMpesaStkpushRoute
  '/api/public/mpesa/validation': typeof ApiPublicMpesaValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/approvals': typeof ApprovalsRoute
  '/attendance': typeof AttendanceRoute
  '/fees-policy': typeof FeesPolicyRoute
  '/investors': typeof InvestorsRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/memos': typeof MemosRoute
  '/pettycash': typeof PettycashRoute
  '/policies': typeof PoliciesRoute
  '/portal': typeof PortalRoute
  '/reports': typeof ReportsRoute
  '/savings': typeof SavingsRoute
  '/secret-keys': typeof SecretKeysRoute
  '/shares': typeof SharesRoute
  '/staff': typeof StaffRoute
  '/staff-mgmt': typeof StaffMgmtRoute
  '/support-inbox': typeof SupportInboxRoute
  '/transactions': typeof TransactionsRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/scan-mpesa': typeof ApiAiScanMpesaRoute
  '/api/mpesa/queue': typeof ApiMpesaQueueRoute
  '/api/public/mpesa/confirmation': typeof ApiPublicMpesaConfirmationRoute
  '/api/public/mpesa/diagnose': typeof ApiPublicMpesaDiagnoseRoute
  '/api/public/mpesa/stkpush': typeof ApiPublicMpesaStkpushRoute
  '/api/public/mpesa/validation': typeof ApiPublicMpesaValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/approvals'
    | '/attendance'
    | '/fees-policy'
    | '/investors'
    | '/loans'
    | '/login'
    | '/members'
    | '/memos'
    | '/pettycash'
    | '/policies'
    | '/portal'
    | '/reports'
    | '/savings'
    | '/secret-keys'
    | '/shares'
    | '/staff'
    | '/staff-mgmt'
    | '/support-inbox'
    | '/transactions'
    | '/api/ai/chat'
    | '/api/ai/scan-mpesa'
    | '/api/mpesa/queue'
    | '/api/public/mpesa/confirmation'
    | '/api/public/mpesa/diagnose'
    | '/api/public/mpesa/stkpush'
    | '/api/public/mpesa/validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/approvals'
    | '/attendance'
    | '/fees-policy'
    | '/investors'
    | '/loans'
    | '/login'
    | '/members'
    | '/memos'
    | '/pettycash'
    | '/policies'
    | '/portal'
    | '/reports'
    | '/savings'
    | '/secret-keys'
    | '/shares'
    | '/staff'
    | '/staff-mgmt'
    | '/support-inbox'
    | '/transactions'
    | '/api/ai/chat'
    | '/api/ai/scan-mpesa'
    | '/api/mpesa/queue'
    | '/api/public/mpesa/confirmation'
    | '/api/public/mpesa/diagnose'
    | '/api/public/mpesa/stkpush'
    | '/api/public/mpesa/validation'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/approvals'
    | '/attendance'
    | '/fees-policy'
    | '/investors'
    | '/loans'
    | '/login'
    | '/members'
    | '/memos'
    | '/pettycash'
    | '/policies'
    | '/portal'
    | '/reports'
    | '/savings'
    | '/secret-keys'
    | '/shares'
    | '/staff'
    | '/staff-mgmt'
    | '/support-inbox'
    | '/transactions'
    | '/api/ai/chat'
    | '/api/ai/scan-mpesa'
    | '/api/mpesa/queue'
    | '/api/public/mpesa/confirmation'
    | '/api/public/mpesa/diagnose'
    | '/api/public/mpesa/stkpush'
    | '/api/public/mpesa/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AttendanceRoute: typeof AttendanceRoute
  FeesPolicyRoute: typeof FeesPolicyRoute
  InvestorsRoute: typeof InvestorsRoute
  LoansRoute: typeof LoansRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  MemosRoute: typeof MemosRoute
  PettycashRoute: typeof PettycashRoute
  PoliciesRoute: typeof PoliciesRoute
  PortalRoute: typeof PortalRoute
  ReportsRoute: typeof ReportsRoute
  SavingsRoute: typeof SavingsRoute
  SecretKeysRoute: typeof SecretKeysRoute
  SharesRoute: typeof SharesRoute
  StaffRoute: typeof StaffRoute
  StaffMgmtRoute: typeof StaffMgmtRoute
  SupportInboxRoute: typeof SupportInboxRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiScanMpesaRoute: typeof ApiAiScanMpesaRoute
  ApiMpesaQueueRoute: typeof ApiMpesaQueueRoute
  ApiPublicMpesaConfirmationRoute: typeof ApiPublicMpesaConfirmationRoute
  ApiPublicMpesaDiagnoseRoute: typeof ApiPublicMpesaDiagnoseRoute
  ApiPublicMpesaStkpushRoute: typeof ApiPublicMpesaStkpushRoute
  ApiPublicMpesaValidationRoute: typeof ApiPublicMpesaValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-inbox': {
      id: '/support-inbox'
      path: '/support-inbox'
      fullPath: '/support-inbox'
      preLoaderRoute: typeof SupportInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-mgmt': {
      id: '/staff-mgmt'
      path: '/staff-mgmt'
      fullPath: '/staff-mgmt'
      preLoaderRoute: typeof StaffMgmtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shares': {
      id: '/shares'
      path: '/shares'
      fullPath: '/shares'
      preLoaderRoute: typeof SharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret-keys': {
      id: '/secret-keys'
      path: '/secret-keys'
      fullPath: '/secret-keys'
      preLoaderRoute: typeof SecretKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pettycash': {
      id: '/pettycash'
      path: '/pettycash'
      fullPath: '/pettycash'
      preLoaderRoute: typeof PettycashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos': {
      id: '/memos'
      path: '/memos'
      fullPath: '/memos'
      preLoaderRoute: typeof MemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees-policy': {
      id: '/fees-policy'
      path: '/fees-policy'
      fullPath: '/fees-policy'
      preLoaderRoute: typeof FeesPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa/queue': {
      id: '/api/mpesa/queue'
      path: '/api/mpesa/queue'
      fullPath: '/api/mpesa/queue'
      preLoaderRoute: typeof ApiMpesaQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/scan-mpesa': {
      id: '/api/ai/scan-mpesa'
      path: '/api/ai/scan-mpesa'
      fullPath: '/api/ai/scan-mpesa'
      preLoaderRoute: typeof ApiAiScanMpesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/validation': {
      id: '/api/public/mpesa/validation'
      path: '/api/public/mpesa/validation'
      fullPath: '/api/public/mpesa/validation'
      preLoaderRoute: typeof ApiPublicMpesaValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/stkpush': {
      id: '/api/public/mpesa/stkpush'
      path: '/api/public/mpesa/stkpush'
      fullPath: '/api/public/mpesa/stkpush'
      preLoaderRoute: typeof ApiPublicMpesaStkpushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/diagnose': {
      id: '/api/public/mpesa/diagnose'
      path: '/api/public/mpesa/diagnose'
      fullPath: '/api/public/mpesa/diagnose'
      preLoaderRoute: typeof ApiPublicMpesaDiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/confirmation': {
      id: '/api/public/mpesa/confirmation'
      path: '/api/public/mpesa/confirmation'
      fullPath: '/api/public/mpesa/confirmation'
      preLoaderRoute: typeof ApiPublicMpesaConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  ApprovalsRoute: ApprovalsRoute,
  AttendanceRoute: AttendanceRoute,
  FeesPolicyRoute: FeesPolicyRoute,
  InvestorsRoute: InvestorsRoute,
  LoansRoute: LoansRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  MemosRoute: MemosRoute,
  PettycashRoute: PettycashRoute,
  PoliciesRoute: PoliciesRoute,
  PortalRoute: PortalRoute,
  ReportsRoute: ReportsRoute,
  SavingsRoute: SavingsRoute,
  SecretKeysRoute: SecretKeysRoute,
  SharesRoute: SharesRoute,
  StaffRoute: StaffRoute,
  StaffMgmtRoute: StaffMgmtRoute,
  SupportInboxRoute: SupportInboxRoute,
  TransactionsRoute: TransactionsRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiScanMpesaRoute: ApiAiScanMpesaRoute,
  ApiMpesaQueueRoute: ApiMpesaQueueRoute,
  ApiPublicMpesaConfirmationRoute: ApiPublicMpesaConfirmationRoute,
  ApiPublicMpesaDiagnoseRoute: ApiPublicMpesaDiagnoseRoute,
  ApiPublicMpesaStkpushRoute: ApiPublicMpesaStkpushRoute,
  ApiPublicMpesaValidationRoute: ApiPublicMpesaValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
